# Generated by Django 5.2.1 on 2025-05-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='original_cart',
            field=models.TextField(default=''),
        ),
    ]
