# Generated by Django 5.2.1 on 2025-05-13 20:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_purchase_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
