# Generated by Django 3.2.25 on 2025-05-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20250508_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank, autogenerates from the title.', unique=True),
        ),
    ]
