# Generated by Django 3.2.25 on 2025-05-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank, autogenerates from the title.', max_length=100, unique=True),
        ),
    ]
