# Generated by Django 5.2.1 on 2025-05-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_frame',
            field=models.CharField(choices=[('1w', '1 Week'), ('2w', '2 Weeks'), ('3w', '3 Weeks'), ('1m', '1 Month'), ('2m', '2 Months'), ('3m', '3 Months')], default='2w', help_text='Estimated time to complete the course with consistent practice', max_length=2),
        ),
    ]
