# Generated by Django 3.2.25 on 2025-05-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank, autogenerates from the title.', unique=True),
        ),
    ]
