# Generated by Django 5.2.1 on 2025-05-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0003_alter_bundle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='bundle',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
    ]
