# Generated by Django 5.2.1 on 2025-05-20 20:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0004_bundle_savings_bundle_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
