from django.test import TestCase
from decimal import Decimal

from bundles.models import Bundle
from courses.models import Course

# Create your tests here.


class TestBundle(TestCase):
    def setUp(self):
        self.course1 = Course.objects.create(title="Course 1", price=10.00)
        self.course2 = Course.objects.create(title="Course 2", price=20.00)
        self.bundle = Bundle.objects.create(
            title="Test Bundle",
            description="A test bundle",
            price=Decimal("25.00")
        )
        self.bundle.courses.set([self.course1, self.course2])

    def test_str_returns_title(self):
        self.assertEqual(str(self.bundle), "Test Bundle")

    def test_slug_autogenerated(self):
        self.assertEqual(self.bundle.slug, "test-bundle")

    def test_get_course_count(self):
        self.assertEqual(self.bundle.get_courses_count(), 2)


if __name__ == "__main__":
    import unittest
    unittest.main()
