from django.test import TestCase
from decimal import Decimal
from courses.models import Course, Category

# Create your tests here.


class TestCourseModels(TestCase):
    """
    Test the Course and the Category models
    """
    def setUp(self):
        self.category = Category.objects.create(name="Obedience")
        self.course = Course.objects.create(
            title="Loose Leash Walking",
            description="How to walk your dog without pulling",
            content="Content and more content",
            price=Decimal("9.99"),
            category=self.category,
            time_frame='2w'
        )

    def test_str_returns_title(self):
        # test that __str__ returns the course title
        self.assertEqual(str(self.course), "Loose Leash Walking")

    def test_slug_autogenerated(self):
        # test that the slug is generated correctly from title
        self.assertEqual(self.course.slug, "loose-leash-walking")

    def test_category_slug_autogenerated(self):
        # test if the slug is autogenerated for categories
        self.assertEqual(self.category.slug, "obedience")

    def test_course_duration_display(self):
        # test the time-frame
        self.assertEqual(self.course.get_time_frame_display(), "2 Weeks")
